import { Dimensions, Platform, StyleSheet } from "react-native";


const { width: screenWidth, height: screenHeight } = Dimensions.get("window");



const modalStyles = StyleSheet.create({
    overlay: { flex: 1, backgroundColor: "rgba(0, 0, 0, 0.45)" },
    bottomSheetContainer: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      maxHeight: screenHeight * 0.9,
      backgroundColor: "white",
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingBottom: Platform.OS === "ios" ? 34 : 16,
      paddingHorizontal: 16,
    },
    handle: {
      width: 48,
      height: 5,
      backgroundColor: "#D1D5DB",
      borderRadius: 2.5,
      alignSelf: "center",
      marginTop: 10,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    titleContainer: { flexDirection: "row", alignItems: "center" },
    title: { fontSize: 20, fontWeight: "700", color: "#1F2937", marginLeft: 12 },
    closeButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: "#F3F4F6",
      alignItems: "center",
      justifyContent: "center",
    },
    content: { paddingBottom: 32 },
    driverIdContainer: { marginBottom: 20 },
    fieldLabel: { fontSize: 14, fontWeight: "600", color: "#374151", marginBottom: 8 },
    driverIdBadge: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#EEF2FF",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
    },
    driverIdText: { fontSize: 14, fontWeight: "600", color: "#6366F1", marginLeft: 8 },
    switchContainer: { marginBottom: 20 },
    switchRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: "#F9FAFB",
      padding: 12,
      borderRadius: 12,
    },
    switchOption: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 8,
      paddingVertical: 6,
      borderRadius: 8,
    },
    switchOptionActive: { backgroundColor: "#EEF2FF" },
    switchOptionText: { fontSize: 14, color: "#6B7280", marginLeft: 8, fontWeight: "500" },
    switchOptionTextActive: { color: "#6366F1", fontWeight: "600" },
    inputGroup: { marginBottom: 20 },
    inputContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#F9FAFB",
      borderWidth: 1,
      borderColor: "#E5E7EB",
      borderRadius: 12,
      paddingHorizontal: 12,
    },
    input: { flex: 1, fontSize: 16, color: "#1F2937", paddingVertical: 12, marginLeft: 8 },
    pickupSection: { marginBottom: 20 },
    sectionTitle: { fontSize: 16, fontWeight: "600", color: "#1F2937", marginBottom: 12 },
    pickupItem: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      backgroundColor: "#F9FAFB",
      borderRadius: 12,
      marginBottom: 8,
    },
    pickupInfo: { flex: 1, marginLeft: 12 },
    pickupText: { fontSize: 16, fontWeight: "600", color: "#1F2937" },
    pickupSubText: { fontSize: 14, color: "#6B7280", marginTop: 4 },
    noPickupsText: { fontSize: 14, color: "#6B7280", textAlign: "center", paddingVertical: 16 },
    errorContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#FEF2F2",
      padding: 12,
      borderRadius: 8,
      marginBottom: 20,
    },
    errorText: { flex: 1, fontSize: 14, color: "#EF4444", marginLeft: 8 },
    optimizeButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#6366F1",
      paddingVertical: 16,
      borderRadius: 12,
      gap: 8,
    },
    optimizeButtonDisabled: { backgroundColor: "#9CA3AF" },
    optimizeButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "600" },
    confirmationContainer: {
      backgroundColor: "#FFFFFF",
      borderRadius: 16,
      padding: 20,
      marginHorizontal: 20,
      alignSelf: "center",
    },
    confirmationTitle: { fontSize: 18, fontWeight: "700", color: "#1F2937", marginBottom: 12 },
    confirmationText: { fontSize: 14, color: "#6B7280", marginBottom: 20 },
    confirmationButtons: { flexDirection: "row", justifyContent: "flex-end", gap: 12 },
    cancelButton: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      backgroundColor: "#F3F4F6",
      borderRadius: 8,
    },
    cancelButtonText: { color: "#6B7280", fontWeight: "600" },
    confirmButton: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      backgroundColor: "#6366F1",
      borderRadius: 8,
    },
    confirmButtonText: { color: "#FFFFFF", fontWeight: "600" },
  })

  export default modalStyles